// Mock product data with realistic names and details
export const mockProducts = [
  {
    id: "game-1",
    title: "Elden Ring",
    description: "An action RPG developed by FromSoftware and published by Bandai Namco Entertainment.",
    image: "/placeholder.svg?height=300&width=300&text=Elden+Ring",
    price: 59.99,
    discount: 25,
    platform: "Steam",
    category: "games",
    publisher: "Bandai Namco",
    releaseDate: "2022-02-25",
    genres: ["Action", "RPG", "Open World"],
    rating: 4.8,
    sales: 12000000,
    features: ["Open World", "Multiplayer", "Controller Support"],
  },
  {
    id: "game-2",
    title: "Cyberpunk 2077",
    description:
      "An open-world, action-adventure RPG set in Night City, a megalopolis obsessed with power, glamour and body modification.",
    image: "/placeholder.svg?height=300&width=300&text=Cyberpunk+2077",
    price: 59.99,
    discount: 50,
    platform: "GOG",
    category: "games",
    publisher: "CD Projekt RED",
    releaseDate: "2020-12-10",
    genres: ["RPG", "Open World", "Sci-Fi"],
    rating: 3.9,
    sales: 18000000,
    features: ["Open World", "Single-player", "Story Rich"],
  },
  {
    id: "game-3",
    title: "Red Dead Redemption 2",
    description:
      "An epic tale of life in America's unforgiving heartland. The game's vast and atmospheric world also provides the foundation for a brand new online multiplayer experience.",
    image: "/placeholder.svg?height=300&width=300&text=RDR2",
    price: 59.99,
    discount: 40,
    platform: "Epic Games",
    category: "games",
    publisher: "Rockstar Games",
    releaseDate: "2019-11-05",
    genres: ["Action", "Adventure", "Open World"],
    rating: 4.9,
    sales: 45000000,
    features: ["Open World", "Multiplayer", "Story Rich"],
  },
  {
    id: "game-4",
    title: "FIFA 23",
    description: "Experience the world's game with over 19,000 players, 700+ teams, 100+ stadiums, and 30+ leagues.",
    image: "/placeholder.svg?height=300&width=300&text=FIFA+23",
    price: 69.99,
    discount: 35,
    platform: "Origin",
    category: "games",
    publisher: "Electronic Arts",
    releaseDate: "2022-09-30",
    genres: ["Sports", "Simulation"],
    rating: 4.2,
    sales: 10000000,
    features: ["Multiplayer", "Controller Support", "Online Competitive"],
  },
  {
    id: "game-5",
    title: "The Witcher 3: Wild Hunt",
    description: "A story-driven, open world adventure set in a dark fantasy universe.",
    image: "/placeholder.svg?height=300&width=300&text=Witcher+3",
    price: 39.99,
    discount: 70,
    platform: "Steam",
    category: "games",
    publisher: "CD Projekt RED",
    releaseDate: "2015-05-19",
    genres: ["RPG", "Open World", "Fantasy"],
    rating: 4.9,
    sales: 40000000,
    features: ["Open World", "Story Rich", "Atmospheric"],
  },
  {
    id: "game-6",
    title: "Battlefield 2042",
    description: "A first-person shooter that marks the return to the iconic all-out warfare of the franchise.",
    image: "/placeholder.svg?height=300&width=300&text=Battlefield+2042",
    price: 59.99,
    discount: 60,
    platform: "Origin",
    category: "games",
    publisher: "Electronic Arts",
    releaseDate: "2021-11-19",
    genres: ["FPS", "Action", "Multiplayer"],
    rating: 3.2,
    sales: 4500000,
    features: ["Multiplayer", "FPS", "Action"],
  },
  {
    id: "game-7",
    title: "Hollow Knight",
    description:
      "A challenging 2D action-adventure. Explore twisting caverns, battle tainted creatures and escape intricate traps.",
    image: "/placeholder.svg?height=300&width=300&text=Hollow+Knight",
    price: 14.99,
    discount: 50,
    platform: "Steam",
    category: "games",
    publisher: "Team Cherry",
    releaseDate: "2017-02-24",
    genres: ["Metroidvania", "Indie", "Action"],
    rating: 4.9,
    sales: 3000000,
    features: ["Atmospheric", "Difficult", "Great Soundtrack"],
  },
  {
    id: "game-8",
    title: "Hades",
    description:
      "A god-like rogue-like dungeon crawler that combines the best aspects of Supergiant's critically acclaimed titles.",
    image: "/placeholder.svg?height=300&width=300&text=Hades",
    price: 24.99,
    discount: 30,
    platform: "Epic Games",
    category: "games",
    publisher: "Supergiant Games",
    releaseDate: "2020-09-17",
    genres: ["Roguelike", "Indie", "Action"],
    rating: 4.8,
    sales: 1000000,
    features: ["Great Soundtrack", "Action Roguelike", "Story Rich"],
  },
  {
    id: "software-1",
    title: "Microsoft Office 2023",
    description: "The latest version of Microsoft Office with Word, Excel, PowerPoint, and more.",
    image: "/placeholder.svg?height=300&width=300&text=Office+2023",
    price: 149.99,
    discount: 20,
    platform: "Windows",
    category: "software",
    publisher: "Microsoft",
    releaseDate: "2022-10-05",
    genres: ["Productivity", "Business"],
    rating: 4.5,
    sales: 8000000,
    features: ["Word Processing", "Spreadsheets", "Presentations"],
  },
  {
    id: "software-2",
    title: "Adobe Creative Cloud",
    description:
      "A collection of 20+ desktop and mobile apps and services for photography, design, video, web, UX, and more.",
    image: "/placeholder.svg?height=300&width=300&text=Adobe+CC",
    price: 52.99,
    discount: 15,
    platform: "Cross-platform",
    category: "software",
    publisher: "Adobe",
    releaseDate: "2022-01-15",
    genres: ["Creative", "Design", "Photography"],
    rating: 4.7,
    sales: 5000000,
    features: ["Photoshop", "Illustrator", "Premiere Pro"],
  },
  {
    id: "software-3",
    title: "Windows 11 Pro",
    description: "The latest version of Windows with advanced security and management features.",
    image: "/placeholder.svg?height=300&width=300&text=Windows+11",
    price: 199.99,
    discount: 10,
    platform: "Windows",
    category: "software",
    publisher: "Microsoft",
    releaseDate: "2021-10-05",
    genres: ["Operating System", "Productivity"],
    rating: 4.3,
    sales: 20000000,
    features: ["Enhanced Security", "Virtual Desktops", "Microsoft Store"],
  },
  {
    id: "software-4",
    title: "Autodesk Maya 2023",
    description: "3D animation, modeling, simulation, and rendering software for film, TV, and games.",
    image: "/placeholder.svg?height=300&width=300&text=Maya+2023",
    price: 205.0,
    discount: 25,
    platform: "Windows/Mac",
    category: "software",
    publisher: "Autodesk",
    releaseDate: "2022-03-29",
    genres: ["3D Modeling", "Animation", "Design"],
    rating: 4.6,
    sales: 1000000,
    features: ["3D Modeling", "Animation", "Visual Effects"],
  },
  {
    id: "software-5",
    title: "Norton 360 Deluxe",
    description: "Comprehensive protection for your devices and online privacy.",
    image: "/placeholder.svg?height=300&width=300&text=Norton+360",
    price: 89.99,
    discount: 50,
    platform: "Cross-platform",
    category: "software",
    publisher: "NortonLifeLock",
    releaseDate: "2022-05-17",
    genres: ["Security", "Antivirus"],
    rating: 4.2,
    sales: 3000000,
    features: ["Real-time Protection", "VPN", "Password Manager"],
  },
  {
    id: "digital-1",
    title: "Steam Wallet $50",
    description: "Add funds to your Steam Wallet to purchase games, software, and more on Steam.",
    image: "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
    price: 50.0,
    discount: 5,
    platform: "Steam",
    category: "digital",
    publisher: "Valve",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Digital Currency"],
    rating: 4.9,
    sales: 15000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
  },
  {
    id: "digital-2",
    title: "Xbox Game Pass Ultimate (3 Months)",
    description: "Get unlimited access to over 100 high-quality games on console, PC, and cloud.",
    image: "/placeholder.svg?height=300&width=300&text=Game+Pass",
    price: 44.99,
    discount: 30,
    platform: "Xbox",
    category: "digital",
    publisher: "Microsoft",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Gaming Service"],
    rating: 4.8,
    sales: 10000000,
    features: ["Xbox Live Gold", "EA Play", "Cloud Gaming"],
  },
  {
    id: "digital-3",
    title: "PlayStation Plus (12 Months)",
    description:
      "Enhance your PlayStation experience with online multiplayer, monthly games, exclusive discounts, and more.",
    image: "/placeholder.svg?height=300&width=300&text=PS+Plus",
    price: 59.99,
    discount: 20,
    platform: "PlayStation",
    category: "digital",
    publisher: "Sony",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Gaming Service"],
    rating: 4.7,
    sales: 9000000,
    features: ["Online Multiplayer", "Monthly Games", "Exclusive Discounts"],
  },
  {
    id: "digital-4",
    title: "Spotify Premium (12 Months)",
    description: "Ad-free music listening, offline playback, and on-demand playback.",
    image: "/placeholder.svg?height=300&width=300&text=Spotify",
    price: 99.99,
    discount: 15,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Spotify",
    releaseDate: "2023-01-01",
    genres: ["Subscription", "Music Service"],
    rating: 4.6,
    sales: 20000000,
    features: ["Ad-free", "Offline Listening", "High Quality Audio"],
  },
  {
    id: "digital-5",
    title: "Netflix Gift Card $50",
    description: "Give the gift of unlimited entertainment with a Netflix gift card.",
    image: "/placeholder.svg?height=300&width=300&text=Netflix",
    price: 50.0,
    discount: 0,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Netflix",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Streaming Service"],
    rating: 4.5,
    sales: 25000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
  },
  {
    id: "game-9",
    title: "The Sims 4",
    description: "A life simulation game that gives players the ability to create and control people.",
    image: "/placeholder.svg?height=300&width=300&text=Sims+4",
    price: 39.99,
    discount: 75,
    platform: "Origin",
    category: "games",
    publisher: "Electronic Arts",
    releaseDate: "2014-09-02",
    genres: ["Simulation", "Casual"],
    rating: 4.4,
    sales: 36000000,
    features: ["Character Customization", "Building", "Mods Support"],
  },
  {
    id: "game-10",
    title: "Stardew Valley",
    description: "An open-ended country-life RPG with charming characters and a delightful rural setting.",
    image: "/placeholder.svg?height=300&width=300&text=Stardew+Valley",
    price: 14.99,
    discount: 40,
    platform: "Steam",
    category: "games",
    publisher: "ConcernedApe",
    releaseDate: "2016-02-26",
    genres: ["Simulation", "RPG", "Indie"],
    rating: 4.9,
    sales: 15000000,
    features: ["Farming", "Multiplayer", "Pixel Graphics"],
  },
  {
    id: "software-6",
    title: "Parallels Desktop 18",
    description: "Run Windows on Mac without rebooting. Fast, simple and powerful.",
    image: "/placeholder.svg?height=300&width=300&text=Parallels",
    price: 79.99,
    discount: 20,
    platform: "Mac",
    category: "software",
    publisher: "Parallels",
    releaseDate: "2022-08-16",
    genres: ["Utility", "Virtualization"],
    rating: 4.5,
    sales: 2000000,
    features: ["Windows on Mac", "Seamless Integration", "Performance Optimization"],
  },
  {
    id: "digital-6",
    title: "Roblox Gift Card $25",
    description: "Get Robux to purchase avatars, accessories, and more in Roblox.",
    image: "/placeholder.svg?height=300&width=300&text=Roblox",
    price: 25.0,
    discount: 0,
    platform: "Cross-platform",
    category: "digital",
    publisher: "Roblox Corporation",
    releaseDate: "2023-01-01",
    genres: ["Gift Card", "Gaming Currency"],
    rating: 4.7,
    sales: 30000000,
    features: ["Instant Delivery", "No Expiration", "Global Usage"],
  },
]

// Mock publisher data
export const mockPublishers = [
  {
    id: "publisher-1",
    name: "Electronic Arts",
    logo: "/placeholder.svg?height=200&width=200&text=EA",
    description:
      "Electronic Arts Inc. is an American video game company headquartered in Redwood City, California. It is the second-largest gaming company in the Americas and Europe by revenue and market capitalization after Activision Blizzard and ahead of Take-Two Interactive, CD Projekt, and Ubisoft as of May 2020.",
    founded: "1982",
    headquarters: "Redwood City, California, USA",
    website: "https://www.ea.com",
    products: ["FIFA", "Battlefield", "The Sims", "Apex Legends", "Mass Effect"],
    featuredProducts: [
      {
        id: "game-4",
        title: "FIFA 23",
        image: "/placeholder.svg?height=300&width=300&text=FIFA+23",
        discount: 35,
      },
      {
        id: "game-6",
        title: "Battlefield 2042",
        image: "/placeholder.svg?height=300&width=300&text=Battlefield+2042",
        discount: 60,
      },
      {
        id: "game-9",
        title: "The Sims 4",
        image: "/placeholder.svg?height=300&width=300&text=Sims+4",
        discount: 75,
      },
    ],
  },
  {
    id: "publisher-2",
    name: "Microsoft",
    logo: "/placeholder.svg?height=200&width=200&text=Microsoft",
    description:
      "Microsoft Corporation is an American multinational technology corporation which produces computer software, consumer electronics, personal computers, and related services.",
    founded: "1975",
    headquarters: "Redmond, Washington, USA",
    website: "https://www.microsoft.com",
    products: ["Windows", "Office", "Xbox", "Surface", "Azure"],
    featuredProducts: [
      {
        id: "software-1",
        title: "Microsoft Office 2023",
        image: "/placeholder.svg?height=300&width=300&text=Office+2023",
        discount: 20,
      },
      {
        id: "software-3",
        title: "Windows 11 Pro",
        image: "/placeholder.svg?height=300&width=300&text=Windows+11",
        discount: 10,
      },
      {
        id: "digital-2",
        title: "Xbox Game Pass Ultimate (3 Months)",
        image: "/placeholder.svg?height=300&width=300&text=Game+Pass",
        discount: 30,
      },
    ],
  },
  {
    id: "publisher-3",
    name: "CD Projekt RED",
    logo: "/placeholder.svg?height=200&width=200&text=CDPR",
    description:
      "CD Projekt S.A. is a Polish video game developer, publisher and distributor based in Warsaw, founded in May 1994 by Marcin Iwiński and Michał Kiciński.",
    founded: "1994",
    headquarters: "Warsaw, Poland",
    website: "https://www.cdprojekt.com",
    products: ["The Witcher", "Cyberpunk 2077", "GWENT"],
    featuredProducts: [
      {
        id: "game-2",
        title: "Cyberpunk 2077",
        image: "/placeholder.svg?height=300&width=300&text=Cyberpunk+2077",
        discount: 50,
      },
      {
        id: "game-5",
        title: "The Witcher 3: Wild Hunt",
        image: "/placeholder.svg?height=300&width=300&text=Witcher+3",
        discount: 70,
      },
    ],
  },
  {
    id: "publisher-4",
    name: "Adobe",
    logo: "/placeholder.svg?height=200&width=200&text=Adobe",
    description:
      "Adobe Inc. is an American multinational computer software company. It has historically focused upon the creation of multimedia and creativity software products.",
    founded: "1982",
    headquarters: "San Jose, California, USA",
    website: "https://www.adobe.com",
    products: ["Photoshop", "Illustrator", "Premiere Pro", "After Effects", "Acrobat"],
    featuredProducts: [
      {
        id: "software-2",
        title: "Adobe Creative Cloud",
        image: "/placeholder.svg?height=300&width=300&text=Adobe+CC",
        discount: 15,
      },
    ],
  },
  {
    id: "publisher-5",
    name: "Valve",
    logo: "/placeholder.svg?height=200&width=200&text=Valve",
    description:
      "Valve Corporation is an American video game developer, publisher, and digital distribution company headquartered in Bellevue, Washington.",
    founded: "1996",
    headquarters: "Bellevue, Washington, USA",
    website: "https://www.valvesoftware.com",
    products: ["Half-Life", "Counter-Strike", "Portal", "Dota 2", "Steam"],
    featuredProducts: [
      {
        id: "digital-1",
        title: "Steam Wallet $50",
        image: "/placeholder.svg?height=300&width=300&text=Steam+Wallet",
        discount: 5,
      },
    ],
  },
]

// Mock user data
export const mockUsers = [
  {
    id: "user-1",
    name: "John Doe",
    email: "john.doe@example.com",
    avatar: "/placeholder.svg?height=100&width=100&text=JD",
    password: "hashed_password_here", // In a real app, this would be properly hashed
    wishlist: ["game-1", "software-2", "digital-3"],
    cart: ["game-4", "software-1"],
    orders: [
      {
        id: "order-1",
        date: "2023-03-15",
        total: 59.99,
        status: "completed",
        items: [
          {
            id: "game-5",
            title: "The Witcher 3: Wild Hunt",
            price: 39.99,
            discount: 70,
            platform: "Steam",
          },
        ],
      },
      {
        id: "order-2",
        date: "2023-02-28",
        total: 149.99,
        status: "completed",
        items: [
          {
            id: "software-1",
            title: "Microsoft Office 2023",
            price: 149.99,
            discount: 20,
            platform: "Windows",
          },
        ],
      },
    ],
    settings: {
      notifications: true,
      newsletter: false,
      darkMode: false,
    },
  },
]

